# TCL File Generated by Component Editor 14.0
# Sun Oct 05 00:01:13 CST 2014
# DO NOT MODIFY


# 
# GPGPU_component "GPGPU_component" v1.0
# ajblane 2014.10.05.00:01:13
# The GPGPU is created by Jeff Bush. Its Qsys component is created by AJ.
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module GPGPU_component
# 
set_module_property DESCRIPTION "The GPGPU is created by Jeff Bush. Its Qsys component is created by AJ."
set_module_property NAME GPGPU_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP System
set_module_property AUTHOR ajblane
set_module_property DISPLAY_NAME GPGPU_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fpga_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS true
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file arbiter.sv SYSTEM_VERILOG PATH arbiter.sv
add_fileset_file async_fifo.sv SYSTEM_VERILOG PATH async_fifo.sv
add_fileset_file axi_async_bridge.sv SYSTEM_VERILOG PATH axi_async_bridge.sv
add_fileset_file axi_interconnect.sv SYSTEM_VERILOG PATH axi_interconnect.sv
add_fileset_file axi_internal_ram.sv SYSTEM_VERILOG PATH axi_internal_ram.sv
add_fileset_file cache_lru.sv SYSTEM_VERILOG PATH cache_lru.sv
add_fileset_file cache_valid_array.sv SYSTEM_VERILOG PATH cache_valid_array.sv
add_fileset_file cam.sv SYSTEM_VERILOG PATH cam.sv
add_fileset_file control_registers.sv SYSTEM_VERILOG PATH control_registers.sv
add_fileset_file core.sv SYSTEM_VERILOG PATH core.sv
add_fileset_file debug_trace.sv SYSTEM_VERILOG PATH debug_trace.sv
add_fileset_file decode_stage.sv SYSTEM_VERILOG PATH decode_stage.sv
add_fileset_file defines.sv SYSTEM_VERILOG PATH defines.sv
add_fileset_file endian_swapper.sv SYSTEM_VERILOG PATH endian_swapper.sv
add_fileset_file execute_stage.sv SYSTEM_VERILOG PATH execute_stage.sv
add_fileset_file fp_adder_stage1.sv SYSTEM_VERILOG PATH fp_adder_stage1.sv
add_fileset_file fp_adder_stage2.sv SYSTEM_VERILOG PATH fp_adder_stage2.sv
add_fileset_file fp_adder_stage3.sv SYSTEM_VERILOG PATH fp_adder_stage3.sv
add_fileset_file fp_multiplier_stage1.sv SYSTEM_VERILOG PATH fp_multiplier_stage1.sv
add_fileset_file fp_normalize.sv SYSTEM_VERILOG PATH fp_normalize.sv
add_fileset_file fp_reciprocal_estimate.sv SYSTEM_VERILOG PATH fp_reciprocal_estimate.sv
add_fileset_file fpga_top.sv SYSTEM_VERILOG PATH fpga_top.sv TOP_LEVEL_FILE
add_fileset_file gpgpu.sv SYSTEM_VERILOG PATH gpgpu.sv
add_fileset_file instruction_fetch_stage.sv SYSTEM_VERILOG PATH instruction_fetch_stage.sv
add_fileset_file instruction_pipeline.sv SYSTEM_VERILOG PATH instruction_pipeline.sv
add_fileset_file integer_multiplier.sv SYSTEM_VERILOG PATH integer_multiplier.sv
add_fileset_file jtag.sv SYSTEM_VERILOG PATH jtag.sv
add_fileset_file jtagloader.sv SYSTEM_VERILOG PATH jtagloader.sv
add_fileset_file l1_cache.sv SYSTEM_VERILOG PATH l1_cache.sv
add_fileset_file l1_cache_tag.sv SYSTEM_VERILOG PATH l1_cache_tag.sv
add_fileset_file l1_load_miss_queue.sv SYSTEM_VERILOG PATH l1_load_miss_queue.sv
add_fileset_file l2_cache.sv SYSTEM_VERILOG PATH l2_cache.sv
add_fileset_file l2_cache_arb.sv SYSTEM_VERILOG PATH l2_cache_arb.sv
add_fileset_file l2_cache_bus_interface.sv SYSTEM_VERILOG PATH l2_cache_bus_interface.sv
add_fileset_file l2_cache_dir.sv SYSTEM_VERILOG PATH l2_cache_dir.sv
add_fileset_file l2_cache_pending_miss.sv SYSTEM_VERILOG PATH l2_cache_pending_miss.sv
add_fileset_file l2_cache_read.sv SYSTEM_VERILOG PATH l2_cache_read.sv
add_fileset_file l2_cache_response.sv SYSTEM_VERILOG PATH l2_cache_response.sv
add_fileset_file l2_cache_tag.sv SYSTEM_VERILOG PATH l2_cache_tag.sv
add_fileset_file l2_cache_write.sv SYSTEM_VERILOG PATH l2_cache_write.sv
add_fileset_file l2req_arbiter_mux.sv SYSTEM_VERILOG PATH l2req_arbiter_mux.sv
add_fileset_file mask_unit.sv SYSTEM_VERILOG PATH mask_unit.sv
add_fileset_file memory_access_stage.sv SYSTEM_VERILOG PATH memory_access_stage.sv
add_fileset_file multi_stage_alu.sv SYSTEM_VERILOG PATH multi_stage_alu.sv
add_fileset_file multiplexer.sv SYSTEM_VERILOG PATH multiplexer.sv
add_fileset_file one_hot_to_index.sv SYSTEM_VERILOG PATH one_hot_to_index.sv
add_fileset_file performance_counters.sv SYSTEM_VERILOG PATH performance_counters.sv
add_fileset_file reciprocal_rom.sv SYSTEM_VERILOG PATH reciprocal_rom.sv
add_fileset_file rollback_controller.sv SYSTEM_VERILOG PATH rollback_controller.sv
add_fileset_file scalar_register_file.sv SYSTEM_VERILOG PATH scalar_register_file.sv
add_fileset_file sdram_controller.sv SYSTEM_VERILOG PATH sdram_controller.sv
add_fileset_file single_stage_alu.sv SYSTEM_VERILOG PATH single_stage_alu.sv
add_fileset_file sram_1r1w.sv SYSTEM_VERILOG PATH sram_1r1w.sv
add_fileset_file store_buffer.sv SYSTEM_VERILOG PATH store_buffer.sv
add_fileset_file strand_fsm.sv SYSTEM_VERILOG PATH strand_fsm.sv
add_fileset_file strand_select_stage.sv SYSTEM_VERILOG PATH strand_select_stage.sv
add_fileset_file sync_fifo.sv SYSTEM_VERILOG PATH sync_fifo.sv
add_fileset_file synchronizer.sv SYSTEM_VERILOG PATH synchronizer.sv
add_fileset_file uart.sv SYSTEM_VERILOG PATH uart.sv
add_fileset_file uart_receive.sv SYSTEM_VERILOG PATH uart_receive.sv
add_fileset_file uart_transmit.sv SYSTEM_VERILOG PATH uart_transmit.sv
add_fileset_file vector_bypass_unit.sv SYSTEM_VERILOG PATH vector_bypass_unit.sv
add_fileset_file vector_register_file.sv SYSTEM_VERILOG PATH vector_register_file.sv
add_fileset_file vga_controller.sv SYSTEM_VERILOG PATH vga_controller.sv
add_fileset_file vga_timing_generator.sv SYSTEM_VERILOG PATH vga_timing_generator.sv
add_fileset_file writeback_stage.sv SYSTEM_VERILOG PATH writeback_stage.sv


# 
# parameters
# 
add_parameter AXI_ID_W INTEGER 4
set_parameter_property AXI_ID_W DEFAULT_VALUE 4
set_parameter_property AXI_ID_W DISPLAY_NAME AXI_ID_W
set_parameter_property AXI_ID_W TYPE INTEGER
set_parameter_property AXI_ID_W UNITS None
set_parameter_property AXI_ID_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_ID_W HDL_PARAMETER true
add_parameter AXI_ADDRESS_W POSITIVE 32 ""
set_parameter_property AXI_ADDRESS_W DEFAULT_VALUE 32
set_parameter_property AXI_ADDRESS_W DISPLAY_NAME AXI_ADDRESS_W
set_parameter_property AXI_ADDRESS_W WIDTH ""
set_parameter_property AXI_ADDRESS_W TYPE POSITIVE
set_parameter_property AXI_ADDRESS_W UNITS None
set_parameter_property AXI_ADDRESS_W ALLOWED_RANGES 1:2147483647
set_parameter_property AXI_ADDRESS_W DESCRIPTION ""
set_parameter_property AXI_ADDRESS_W HDL_PARAMETER true
add_parameter AXI_DATA_W INTEGER 32 ""
set_parameter_property AXI_DATA_W DEFAULT_VALUE 32
set_parameter_property AXI_DATA_W DISPLAY_NAME AXI_DATA_W
set_parameter_property AXI_DATA_W WIDTH ""
set_parameter_property AXI_DATA_W TYPE INTEGER
set_parameter_property AXI_DATA_W UNITS None
set_parameter_property AXI_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_DATA_W DESCRIPTION ""
set_parameter_property AXI_DATA_W HDL_PARAMETER true
add_parameter AXI_NUMBYTES INTEGER 4
set_parameter_property AXI_NUMBYTES DEFAULT_VALUE 4
set_parameter_property AXI_NUMBYTES DISPLAY_NAME AXI_NUMBYTES
set_parameter_property AXI_NUMBYTES TYPE INTEGER
set_parameter_property AXI_NUMBYTES UNITS None
set_parameter_property AXI_NUMBYTES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_NUMBYTES HDL_PARAMETER true
add_parameter SDRAM_START_ADDRESS STD_LOGIC_VECTOR 262144 ""
set_parameter_property SDRAM_START_ADDRESS DEFAULT_VALUE 262144
set_parameter_property SDRAM_START_ADDRESS DISPLAY_NAME SDRAM_START_ADDRESS
set_parameter_property SDRAM_START_ADDRESS WIDTH 32
set_parameter_property SDRAM_START_ADDRESS TYPE STD_LOGIC_VECTOR
set_parameter_property SDRAM_START_ADDRESS UNITS None
set_parameter_property SDRAM_START_ADDRESS DESCRIPTION ""
set_parameter_property SDRAM_START_ADDRESS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point altera_axi_master
# 
add_interface altera_axi_master axi start
set_interface_property altera_axi_master associatedClock clock_sink
set_interface_property altera_axi_master associatedReset reset
set_interface_property altera_axi_master readIssuingCapability 1
set_interface_property altera_axi_master writeIssuingCapability 1
set_interface_property altera_axi_master combinedIssuingCapability 1
set_interface_property altera_axi_master ENABLED true
set_interface_property altera_axi_master EXPORT_OF ""
set_interface_property altera_axi_master PORT_NAME_MAP ""
set_interface_property altera_axi_master CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi_master SVD_ADDRESS_GROUP ""

add_interface_port altera_axi_master axm_awid awid Output AXI_ID_W
add_interface_port altera_axi_master axm_awaddr awaddr Output AXI_ADDRESS_W
add_interface_port altera_axi_master axm_awlen awlen Output 4
add_interface_port altera_axi_master axm_awsize awsize Output 3
add_interface_port altera_axi_master axm_awburst awburst Output 2
add_interface_port altera_axi_master axm_awlock awlock Output 2
add_interface_port altera_axi_master axm_awcache awcache Output 4
add_interface_port altera_axi_master axm_awprot awprot Output 3
add_interface_port altera_axi_master axm_awvalid awvalid Output 1
add_interface_port altera_axi_master axm_awready awready Input 1
add_interface_port altera_axi_master axm_wid wid Output AXI_ID_W
add_interface_port altera_axi_master axm_wdata wdata Output AXI_DATA_W
add_interface_port altera_axi_master axm_wstrb wstrb Output AXI_NUMBYTES
add_interface_port altera_axi_master axm_wlast wlast Output 1
add_interface_port altera_axi_master axm_wvalid wvalid Output 1
add_interface_port altera_axi_master axm_wready wready Input 1
add_interface_port altera_axi_master axm_bid bid Input AXI_ID_W
add_interface_port altera_axi_master axm_bresp bresp Input 2
add_interface_port altera_axi_master axm_bvalid bvalid Input 1
add_interface_port altera_axi_master axm_bready bready Output 1
add_interface_port altera_axi_master axm_arid arid Output AXI_ID_W
add_interface_port altera_axi_master axm_araddr araddr Output AXI_ADDRESS_W
add_interface_port altera_axi_master axm_arlen arlen Output 4
add_interface_port altera_axi_master axm_arsize arsize Output 3
add_interface_port altera_axi_master axm_arburst arburst Output 2
add_interface_port altera_axi_master axm_arlock arlock Output 2
add_interface_port altera_axi_master axm_arcache arcache Output 4
add_interface_port altera_axi_master axm_arprot arprot Output 3
add_interface_port altera_axi_master axm_arvalid arvalid Output 1
add_interface_port altera_axi_master axm_arready arready Input 1
add_interface_port altera_axi_master axm_rid rid Input AXI_ID_W
add_interface_port altera_axi_master axm_rdata rdata Input AXI_DATA_W
add_interface_port altera_axi_master axm_rresp rresp Input 2
add_interface_port altera_axi_master axm_rlast rlast Input 1
add_interface_port altera_axi_master axm_rvalid rvalid Input 1
add_interface_port altera_axi_master axm_rready rready Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk50 clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1

